-- DEFERRED — apply only at Snowflake onboarding (swap-back). See ../README.md.
CREATE WAREHOUSE IF NOT EXISTS OBS_WH WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE DATABASE IF NOT EXISTS OBS_DB;
CREATE ROLE IF NOT EXISTS OBS_WRITER;
CREATE ROLE IF NOT EXISTS OBS_READER;
GRANT USAGE ON WAREHOUSE OBS_WH TO ROLE OBS_WRITER;
GRANT USAGE ON DATABASE OBS_DB TO ROLE OBS_READER;
