"""Controlled vocabulary for the `event_type` field — 50 types across 10 categories.

This is the single source of truth, vendored into ai-observability-sdk and the
enrichment/storage consumers. The Enrichment Consumer rejects any event whose
event_type is not a member here (→ dead-letter).
"""
from enum import Enum


class EventType(str, Enum):
    # --- Request (4) ---
    REQUEST_RECEIVED = "REQUEST_RECEIVED"
    REQUEST_COMPLETED = "REQUEST_COMPLETED"
    REQUEST_FAILED = "REQUEST_FAILED"
    RESPONSE_DELIVERED = "RESPONSE_DELIVERED"

    # --- Orchestration (6) ---
    AUTH_COMPLETED = "AUTH_COMPLETED"
    CONFIG_LOADED = "CONFIG_LOADED"
    PLAN_CREATED = "PLAN_CREATED"
    AGENT_EXECUTION_REQUEST_PRODUCED = "AGENT_EXECUTION_REQUEST_PRODUCED"
    FINAL_RESPONSE_CONSUMED = "FINAL_RESPONSE_CONSUMED"
    RESPONSE_BUILT = "RESPONSE_BUILT"

    # --- Kafka (4) ---
    KAFKA_MESSAGE_PRODUCED = "KAFKA_MESSAGE_PRODUCED"
    KAFKA_MESSAGE_CONSUMED = "KAFKA_MESSAGE_CONSUMED"
    KAFKA_MESSAGE_DLQ = "KAFKA_MESSAGE_DLQ"
    KAFKA_LAG_RECORDED = "KAFKA_LAG_RECORDED"

    # --- Agent (8) ---
    AGENT_STARTED = "AGENT_STARTED"
    AGENT_STEP_STARTED = "AGENT_STEP_STARTED"
    AGENT_STEP_COMPLETED = "AGENT_STEP_COMPLETED"
    AGENT_LOOP_ITERATION = "AGENT_LOOP_ITERATION"
    AGENT_HANDOFF = "AGENT_HANDOFF"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    AGENT_FAILED = "AGENT_FAILED"
    AGENT_TIMEOUT = "AGENT_TIMEOUT"

    # --- LLM (5) ---
    LLM_CALL_STARTED = "LLM_CALL_STARTED"
    LLM_CALL_COMPLETED = "LLM_CALL_COMPLETED"
    LLM_CALL_FAILED = "LLM_CALL_FAILED"
    LLM_RATE_LIMITED = "LLM_RATE_LIMITED"
    LLM_SAFETY_BLOCKED = "LLM_SAFETY_BLOCKED"

    # --- Tool (4) ---
    TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
    TOOL_CALL_COMPLETED = "TOOL_CALL_COMPLETED"
    TOOL_CALL_FAILED = "TOOL_CALL_FAILED"
    TOOL_CALL_TIMEOUT = "TOOL_CALL_TIMEOUT"

    # --- RAG (5) ---
    RAG_RETRIEVAL_STARTED = "RAG_RETRIEVAL_STARTED"
    RAG_RETRIEVAL_COMPLETED = "RAG_RETRIEVAL_COMPLETED"
    RAG_RETRIEVAL_FAILED = "RAG_RETRIEVAL_FAILED"
    RAG_NO_RESULT = "RAG_NO_RESULT"
    RAG_INDEX_HEALTH_CHECKED = "RAG_INDEX_HEALTH_CHECKED"

    # --- Guardrail (4) ---
    GUARDRAIL_EVALUATED = "GUARDRAIL_EVALUATED"
    GUARDRAIL_BLOCKED = "GUARDRAIL_BLOCKED"
    GUARDRAIL_REDACTED = "GUARDRAIL_REDACTED"
    GUARDRAIL_ESCALATED = "GUARDRAIL_ESCALATED"

    # --- Feedback (3) ---
    FEEDBACK_SUBMITTED = "FEEDBACK_SUBMITTED"
    FEEDBACK_REVIEWED = "FEEDBACK_REVIEWED"
    FEEDBACK_INCIDENT_TRIGGERED = "FEEDBACK_INCIDENT_TRIGGERED"

    # --- Document / multimodal (7) ---
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_STORED_IN_S3 = "DOCUMENT_STORED_IN_S3"
    DOCUMENT_EXTRACTION_STARTED = "DOCUMENT_EXTRACTION_STARTED"
    DOCUMENT_EXTRACTION_COMPLETED = "DOCUMENT_EXTRACTION_COMPLETED"
    DOCUMENT_EXTRACTION_FAILED = "DOCUMENT_EXTRACTION_FAILED"
    DOCUMENT_INDEXED = "DOCUMENT_INDEXED"
    DOCUMENT_EMBEDDING_CREATED = "DOCUMENT_EMBEDDING_CREATED"


# Guard: the catalog must stay at 50 (see plan.md §15.2 — reconcile the "38" label in the diagram).
assert len(EventType) == 50, f"expected 50 event types, got {len(EventType)}"

VALUES: frozenset[str] = frozenset(e.value for e in EventType)
